#ifndef XFCE_APPLET_SPEED_SYS_BSD_NETWORK_STATS_READER_H
#define XFCE_APPLET_SPEED_SYS_BSD_NETWORK_STATS_READER_H

#error "*BSD not supported"

#endif // XFCE_APPLET_SPEED_SYS_BSD_NETWORK_STATS_READER_H
